'use strict';

/**
 * Image upload routes, mounted at /api/uploads.
 *
 * PERMISSIONS
 *
 * Uploading an image for an entity requires the same `edit` permission as
 * changing that entity, because that is what an upload is for. A user who
 * cannot edit products has no business putting files on the server under
 * `products/`.
 *
 * One concrete route is registered per entity rather than a single
 * `/:entity` handler with a permission chosen at request time. authorize()
 * validates its module name when the middleware is BUILT, so a typo fails at
 * startup instead of silently denying every request - a property that is lost
 * the moment the module name becomes dynamic.
 *
 * WHAT THIS ENDPOINT RETURNS
 *
 * The application path to store on the record, e.g. `/uploads/products/ab….webp`.
 * The caller then saves that value into the entity's existing image column
 * through the normal update endpoint. Upload and assignment are deliberately
 * separate: an image can be uploaded while a form is still being filled in,
 * and a failed save does not lose the file.
 */

const express = require('express');

const uploadController = require('../controllers/upload.controller');
const authenticate = require('../middleware/authenticate');
const authorize = require('../middleware/authorize');
const { uploadSingleImage } = require('../middleware/upload');
const { UPLOAD_ENTITIES } = require('../services/upload.service');
const { ACTIONS } = require('../constants');

const router = express.Router();

router.use(authenticate());

/**
 * @openapi
 * /api/uploads/{entity}:
 *   post:
 *     tags: [Uploads]
 *     summary: Upload an image for an entity
 *     description: >
 *       Stores an image on the server and returns the application path to save
 *       in that entity's existing image column. The same column also accepts an
 *       external `https://` URL, so a record's image may come from either
 *       source and every client reads one field.
 *
 *
 *       The returned `path` is an application path such as
 *       `/uploads/products/9f2c….webp`, served by `GET /uploads/...`. No
 *       filesystem location is exposed, and the storage root can differ
 *       between servers without changing stored values.
 *
 *
 *       The file is accepted only if its leading bytes match a JPEG, PNG, GIF
 *       or WebP signature; the declared content type and the original filename
 *       are not trusted. The stored filename is generated by the server, so an
 *       upload cannot overwrite an existing file or influence its own location.
 *       SVG is rejected because it can carry script.
 *
 *
 *       Requires the `edit` permission for the module that owns the entity:
 *       `banners` → Banners, `categories` → Categories, `products` → Products,
 *       `chains` and `films` → Settings.
 *     parameters:
 *       - in: path
 *         name: entity
 *         required: true
 *         description: Which entity the image belongs to. Determines the folder and the permission required.
 *         schema:
 *           type: string
 *           enum: [banners, categories, chains, films, products]
 *     requestBody:
 *       required: true
 *       content:
 *         multipart/form-data:
 *           schema:
 *             type: object
 *             required: [file]
 *             properties:
 *               file:
 *                 type: string
 *                 format: binary
 *                 description: JPEG, PNG, GIF or WebP. Maximum size is set by MAX_UPLOAD_SIZE_MB (default 5 MB).
 *     responses:
 *       201:
 *         description: Image stored
 *         content:
 *           application/json:
 *             schema:
 *               allOf:
 *                 - $ref: '#/components/schemas/SuccessResponse'
 *                 - type: object
 *                   properties:
 *                     data:
 *                       type: object
 *                       properties:
 *                         path:
 *                           type: string
 *                           example: /uploads/products/9f2c1a7b4d8e6f30a1b2c3d4e5f60718.webp
 *                           description: Save this in the entity's image column.
 *                         mimeType:
 *                           type: string
 *                           example: image/webp
 *                         bytes:
 *                           type: integer
 *                           example: 48213
 *       400: { $ref: '#/components/responses/BadRequest' }
 *       401: { $ref: '#/components/responses/Unauthorized' }
 *       403: { $ref: '#/components/responses/Forbidden' }
 */
for (const [entity, moduleName] of Object.entries(UPLOAD_ENTITIES)) {
  router.post(
    `/${entity}`,
    authorize(moduleName, ACTIONS.EDIT),
    // The entity is fixed by the route, so it cannot be influenced by the
    // request. No validator is needed for it, and the service still checks it
    // against the allowlist before touching the filesystem.
    (req, res, next) => {
      req.uploadEntity = entity;
      next();
    },
    uploadSingleImage(),
    uploadController.uploadImage
  );
}

module.exports = router;
